version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: vhost
    main: ./cmd/vhost
    binary: vhost
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}

archives:
  - id: vhost
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: ksyq12
    name: vhost
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
